/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package resto.gui.objets.dialogs.ajouts;

import java.util.ArrayList;
import java.util.Collection;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import resto.business.AdminFacade;
import resto.gui.objets.element.JPanelIngre;
import resto.outils.Outils;
import resto.persistance.dto.IngredientDto;
import resto.persistance.dto.ListeAlimentDto;
import resto.persistance.dto.RecetteDto;

/**
 *
 * @author Gilles
 */
public class AjoutRecette extends javax.swing.JDialog {

    private Double prixTmp = 0.0;
    private Collection<IngredientDto> lstAli;
    private RecetteDto recette;
    private JPanelIngre lastPanelIngre;
    private IngredientDto lastIng;

    /**
     * Creates new form AjoutRecette
     */
    public AjoutRecette(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        lstAli = new ArrayList<>();
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(this.getClass().getResource("/img/Logo.jpg")).getImage());
        setTitle("Ajout de recette");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelPrixPP = new javax.swing.JLabel();
        jTextNom = new javax.swing.JTextField();
        jTextCouv = new javax.swing.JTextField();
        jButtonAI = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jListIngr = new resto.gui.objets.element.JListeIngredient();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelPrix = new javax.swing.JLabel();
        jLabelPrix2 = new javax.swing.JLabel();
        jLabelPrix3 = new javax.swing.JLabel();
        jButtonSupI = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jLabel1.setText("Nom de la recette :");

        jLabelPrixPP.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jLabelPrixPP.setText("0");

        jTextNom.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N

        jTextCouv.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jTextCouv.setText("1");
        jTextCouv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCouvActionPerformed(evt);
            }
        });

        jButtonAI.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jButtonAI.setText("Ajouter ingrédiant");
        jButtonAI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAIActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jButton1.setText("Ajouter Recette");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jLabel3.setText("Nombre de couverts :");

        jLabel4.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jLabel4.setText("Prix pp :");

        jLabel5.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jLabel5.setText("Prix :");

        jLabelPrix.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jLabelPrix.setText("0");

        jLabelPrix2.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jLabelPrix2.setText("€");

        jLabelPrix3.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jLabelPrix3.setText("€");

        jButtonSupI.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jButtonSupI.setText("Supprimer ingrédiant");
        jButtonSupI.setEnabled(false);
        jButtonSupI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextNom)
                            .addComponent(jTextCouv)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jListIngr, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(34, 34, 34))
                                        .addComponent(jLabel4))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabelPrixPP)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabelPrix3))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabelPrix)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabelPrix2)))
                                    .addGap(15, 15, 15))
                                .addComponent(jButtonAI, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonSupI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextCouv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jListIngr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAI, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSupI, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabelPrix)
                            .addComponent(jLabelPrix2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabelPrixPP)
                            .addComponent(jLabelPrix3))))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextCouvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCouvActionPerformed
        try {
            jLabelPrixPP.setText("" + Outils.round(prixTmp / Integer.parseInt(jTextCouv.getText()), 4));
        } catch (Exception ex) {
            jTextCouv.setText("1");
            JOptionPane.showMessageDialog(null,
                    "Fais attention a ce que tu fais! tu vas tout casser !! n'entre que des chiffres pardi" + ex.getMessage(), "Error Massage",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jTextCouvActionPerformed

    private void jButtonAIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAIActionPerformed
        AjoutIngredient aI = new AjoutIngredient(null, true);
        aI.setVisible(true);
        if (aI.getExit() == 0) {
            lastIng = aI.getIngre();
            lastPanelIngre = new JPanelIngre(lastIng);
            jListIngr.addElem(lastPanelIngre);
            prixTmp += lastIng.getPrix();
            lstAli.add(lastIng);
            jLabelPrix.setText("" + Outils.round(prixTmp, 4));
            jLabelPrixPP.setText("" + Outils.round(prixTmp / Integer.parseInt(jTextCouv.getText()), 4));
            if (!lstAli.isEmpty()) {
                jButtonSupI.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jButtonAIActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            recette = new RecetteDto(0, jTextNom.getText(), new ListeAlimentDto(0, 0, lstAli), prixTmp, Integer.parseInt(jTextCouv.getText()));
            AdminFacade.AjoutRecettes(recette);
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,
                    "Fais attention a ce que tu fais! tu vas tout casser !!\n" + ex.getMessage(), "Error Massage",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonSupIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupIActionPerformed

        if (!lstAli.isEmpty()) {
            jListIngr.removeLastPanel();
            prixTmp -= lastIng.getPrix();
            lstAli.remove(lastIng);
            jLabelPrix.setText("" + Outils.round(prixTmp, 4));
            jLabelPrixPP.setText("" + Outils.round(prixTmp / Integer.parseInt(jTextCouv.getText()), 4));
            if (lstAli.isEmpty()) {
                jButtonSupI.setEnabled(false);
            }
        }
    }//GEN-LAST:event_jButtonSupIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjoutRecette.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjoutRecette.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjoutRecette.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjoutRecette.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AjoutRecette dialog = new AjoutRecette(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAI;
    private javax.swing.JButton jButtonSupI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelPrix;
    private javax.swing.JLabel jLabelPrix2;
    private javax.swing.JLabel jLabelPrix3;
    private javax.swing.JLabel jLabelPrixPP;
    private resto.gui.objets.element.JListeIngredient jListIngr;
    private javax.swing.JTextField jTextCouv;
    private javax.swing.JTextField jTextNom;
    // End of variables declaration//GEN-END:variables
}
