/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package resto.gui.criteres;

import be.esi.alg2.gui.outils.JPCritSelGenerique;
import javax.swing.JOptionPane;
import resto.exception.RestoDTOException;
import resto.seldto.CommandeSel;

/**
 *
 * @author g38302
 */
public class JPCritSelCommande extends JPCritSelGenerique<CommandeSel> {

    public JPCritSelCommande() {
        initComponents();
    }

    @Override
    public void setSel(CommandeSel sel) {
        if (sel == null) {
            jTLibelle.setText("");
        } else {
            jTLibelle.setText(sel.getLibelle());
        }
    }

    @Override
    public CommandeSel getCriteres() {
        CommandeSel e = null;
        try {

            e = new CommandeSel(0, jTLibelle.getText(), null, 0.0, 0);

        } catch (RestoDTOException ex) {
            JOptionPane.showMessageDialog(null,
                    "aaaaaaaaaaaaarrrrrrrrrrggggggggg attention hein  !!\n" + ex.getMessage(), "Error Massage",
                    JOptionPane.ERROR_MESSAGE);
        }
        return e;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTLibelle = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jLabel1.setText("nom du client :");

        jTLibelle.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTLibelle, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(jTLibelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTLibelle;
    // End of variables declaration//GEN-END:variables
}
