/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package client.gui.objets.dialogs.consults;

import client.implementation.FoodClientImpl;
import client.tools.GenericDialog;
import common.dto.CategorieDto;
import common.tools.CaseEnum;
import javax.swing.JOptionPane;

/**
 *
 * @author Gilles
 */
public class MaCategorie extends GenericDialog {

    /**
     * Creates new form MaCategorie
     */
    public MaCategorie(java.awt.Frame parent, boolean modal, FoodClientImpl modele, CategorieDto cat) {
        super(parent, modal, modele, "Apperçu de la catégorie : " + cat.getNom());
        initComponents();
        try {

            this.jLabelNom.setText(cat.getNom());
            this.jLabelELEM.setText(modele.getNbElem(CaseEnum.CATEGORIE, cat) + "");
            this.jLabelSC.setText(modele.getNbElem(CaseEnum.ELEM_SOUS_CATEGORIE,cat) + "");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,
                    "Un problème d'acces au fichier est survenu ... \n" + e.getMessage(), "Error Massage",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelNom = new javax.swing.JLabel();
        jLabelSC = new javax.swing.JLabel();
        jLabelELEM = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jLabel1.setText("Nom :");

        jLabel2.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jLabel2.setText("Nombre de Sous-catégorie associées :");

        jLabel3.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jLabel3.setText("Nombre d'éléments :");

        jLabelNom.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jLabelNom.setText("[NOM]");

        jLabelSC.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jLabelSC.setText("[SOUSCAT]");

        jLabelELEM.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jLabelELEM.setText("[ELEM]");

        jButton2.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jButton2.setText("Quitter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNom)
                    .addComponent(jLabelSC)
                    .addComponent(jLabelELEM)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelSC)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelELEM)))
                .addGap(22, 22, 22)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelELEM;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelSC;
    // End of variables declaration//GEN-END:variables
}
