/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package client.gui.objets.dialogs.consults;

import javax.swing.JOptionPane;
import client.gui.objets.dialogs.MonJFileChooser;
import client.implementation.FoodClientImpl;
import client.tools.ClientTool;
import client.tools.GenericDialog;
import common.dto.CommandeDto;
import common.tools.CommonTool;

/**
 *
 * @author Gilles
 */
public class MaCommande extends GenericDialog {

    private final CommandeDto com;

    public MaCommande(java.awt.Frame parent, boolean modal,FoodClientImpl modele, CommandeDto com) {
        super(parent, modal,modele,"Apperçu de la commande du client : " + com.getLibelle());
        initComponents();
        this.com = com;
        this.jLabelTitre.setText(com.getLibelle());
        this.jLabelPrix.setText("" + CommonTool.round(com.getRecPrix(), 4));
        this.jListeRecette1.setElmnt(com.getListeRecettes(), false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitre = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelPrix = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabelPrix1 = new javax.swing.JLabel();
        jListeRecette1 = new client.gui.objets.element.JListeRecette(modele);
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitre.setFont(new java.awt.Font("Traditional Arabic", 0, 36)); // NOI18N
        jLabelTitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitre.setText("[Titre]");
        jLabelTitre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabelTitre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jLabel2.setText("Prix :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 392, 60, -1));

        jLabelPrix.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jLabelPrix.setText("0");
        getContentPane().add(jLabelPrix, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 392, 70, -1));

        jButton1.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jButton1.setText("Quitter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 503, 183, -1));

        jButton2.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jButton2.setText("Liste ingrédients");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 503, 265, -1));

        jLabelPrix1.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jLabelPrix1.setText("€");
        getContentPane().add(jLabelPrix1, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 392, -1, -1));
        getContentPane().add(jListeRecette1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 68, 455, 317));

        jButton3.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jButton3.setText("Enregistrer sous");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 455, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new MaListeAliments(null, true,modele, com).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       try {
            MonJFileChooser jfc = new MonJFileChooser();
            jfc.setVisible(true);
            ClientTool.enregistrer(jfc.getUrl(), com.getLibelle(), com.getContenu());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,
                    "Un problème d'acces au fichier est survenu ... \n" + ex.getMessage(), "Error Massage",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelPrix;
    private javax.swing.JLabel jLabelPrix1;
    private javax.swing.JLabel jLabelTitre;
    private client.gui.objets.element.JListeRecette jListeRecette1;
    // End of variables declaration//GEN-END:variables
}
