/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package client.gui.objets.dialogs.consults;

import javax.swing.JOptionPane;
import client.gui.objets.dialogs.MonJFileChooser;
import client.implementation.FoodClientImpl;
import client.tools.ClientTool;
import client.tools.GenericDialog;
import common.dto.CommandeDto;
import common.tools.CaseEnum;
import common.tools.CommonTool;
import java.util.ArrayList;

/**
 *
 * @author Gilles
 */
public class MaListeAliments extends GenericDialog {
    
    private CommandeDto com;
    
    public MaListeAliments(java.awt.Frame parent, boolean modal, FoodClientImpl modele, CommandeDto com) {
        super(parent, modal, modele, "Apperçu de la liste d'aliment nécessaire pour le bon de commande de : " + com.getLibelle());
        initComponents();
        try {
            this.com = com;
            this.jLabelTitre.setText(com.getLibelle());
            this.jListeIngredient1.setElmnt(CommonTool.triFournisseur(modele.getIngredientsFromCommande(com)));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,
                    "Fais attention a ce que tu fais! tu vas tout casser !!\n" + ex.getMessage(), "Error Massage",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitre = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jListeIngredient1 = new client.gui.objets.element.JListeIngredient(modele);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelTitre.setFont(new java.awt.Font("Traditional Arabic", 0, 36)); // NOI18N
        jLabelTitre.setText("[Titre]");

        jButton1.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jButton1.setText("Quitter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jButton2.setText("Enregistrer sous");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelTitre)
                    .addComponent(jListeIngredient1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabelTitre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jListeIngredient1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton2});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            MonJFileChooser jfc = new MonJFileChooser();
            jfc.setVisible(true);
            ArrayList<String> contenu = new ArrayList<>(modele.get(CaseEnum.CONTENTENU_LISTE_COMMANDE, com));
            ClientTool.enregistrer(jfc.getUrl(), com.getLibelle() + "Liste", contenu);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,
                    "Un problème d'acces au fichier est survenu ... \n" + ex.getMessage(), "Error Massage",
                    JOptionPane.ERROR_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabelTitre;
    private client.gui.objets.element.JListeIngredient jListeIngredient1;
    // End of variables declaration//GEN-END:variables
}
