/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package client.gui.objets.dialogs.ajouts;

import client.tools.GenericDialog;
import common.dto.IngredientDto;
import common.tools.Quantity;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Gilles
 */
public class AjoutIngredient extends GenericDialog {

    private IngredientDto ingre;
    private int exit = 1;

    /**
     * Creates new form AjoutIngredient
     */
    public AjoutIngredient(java.awt.Frame parent, boolean modal) {
        super(parent, modal,null,"Ajout d'ingrédient");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextQuan = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        selectAliment1 = new client.gui.objets.element.SelectAliment();
        jComboBox1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jLabel1.setText("Selectionner un aliment :");

        jLabel2.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jLabel2.setText("Quantitée :");

        jTextQuan.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jTextQuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextQuanActionPerformed(evt);
            }
        });

        jToggleButton1.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jToggleButton1.setText("Ajouter");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        selectAliment1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                selectAliment1PropertyChange(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        if (selectAliment1.getObjectSelected() != null){
            jComboBox1.setModel(new DefaultComboBoxModel(Quantity.values(selectAliment1.getObjectSelected().getUnit())));
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectAliment1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(selectAliment1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextQuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1))
                .addGap(13, 13, 13)
                .addComponent(jToggleButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextQuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextQuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextQuanActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        try {
            ingre = new IngredientDto(selectAliment1.getObjectSelected(), Integer.parseInt(jTextQuan.getText()), (Quantity) jComboBox1.getSelectedItem());
            this.exit = 0;
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,
                    "n'entre que des chiffres dans le champ quantité sinon ça n'ira pas !!" + ex.getMessage(), "Error Massage",
                    JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void selectAliment1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_selectAliment1PropertyChange
        if (selectAliment1.getObjectSelected() != null) {
            jComboBox1.setModel(new DefaultComboBoxModel(Quantity.values(selectAliment1.getObjectSelected().getUnit())));
        }
    }//GEN-LAST:event_selectAliment1PropertyChange

    public IngredientDto getIngre() {
        return ingre;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextQuan;
    private javax.swing.JToggleButton jToggleButton1;
    private client.gui.objets.element.SelectAliment selectAliment1;
    // End of variables declaration//GEN-END:variables

    public int getExit() {
        return exit;
    }
}
