/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package client.gui.objets.dialogs.ajouts;

import java.util.ArrayList;
import java.util.Collection;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import resto.business.AdminFacade;
import client.gui.objets.element.JPanelComp;
import common.dto.CommandeDto;
import common.dto.ComposantDto;
import common.dto.ListeRecetteDto;
import common.tools.CommonTool;

/**
 *
 * @author Gilles
 */
public class AjoutCommande extends javax.swing.JDialog {

    private Double prixTmp = 0.0;
    private Collection<ComposantDto> lstComp;
    private CommandeDto commande;
    private JPanelComp lastPanelComp;
    private ComposantDto lastComp;

    /**
     * Creates new form AjoutRecette
     */
    public AjoutCommande(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        lstComp = new ArrayList<>();
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Ajout de commande");
        setIconImage(new ImageIcon(this.getClass().getResource("/img/Logo.jpg")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextNom = new javax.swing.JTextField();
        jButtonAI = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabelPrix = new javax.swing.JLabel();
        jLabelPrix2 = new javax.swing.JLabel();
        jButtonSupI = new javax.swing.JButton();
        jListeRecette = new client.gui.objets.element.JListeRecette();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jLabel1.setText("Nom du client :");

        jTextNom.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N

        jButtonAI.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jButtonAI.setText("Ajouter recette");
        jButtonAI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAIActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jButton1.setText("Ajouter bon de commande");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jLabel5.setText("Prix :");

        jLabelPrix.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jLabelPrix.setText("0");

        jLabelPrix2.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jLabelPrix2.setText("€");

        jButtonSupI.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jButtonSupI.setText("Supprimer recette");
        jButtonSupI.setEnabled(false);
        jButtonSupI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextNom))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jListeRecette, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelPrix)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabelPrix2)
                                    .addGap(15, 15, 15))
                                .addComponent(jButtonAI, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonSupI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAI, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSupI, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabelPrix)
                            .addComponent(jLabelPrix2)))
                    .addComponent(jListeRecette, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAIActionPerformed
        AjoutComposant aI = new AjoutComposant(null, true);
        aI.setVisible(true);
        if (aI.getExit() == 0) {
            lastComp = aI.getComp();
            lastPanelComp = new JPanelComp(lastComp);
            jListeRecette.addElem(lastPanelComp);
            prixTmp += lastComp.getPrix();
            lstComp.add(lastComp);
            jLabelPrix.setText("" + CommonTool.round(prixTmp, 4));
            if (!lstComp.isEmpty()) {
                jButtonSupI.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jButtonAIActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            commande = new CommandeDto(0, jTextNom.getText(), new ListeRecetteDto(0, 0, lstComp), prixTmp);
            AdminFacade.AjoutCommande(commande);
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,
                    "Fais attention a ce que tu fais! tu vas tout casser !!" + ex.getMessage(), "Error Massage",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonSupIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupIActionPerformed

        if (!lstComp.isEmpty()) {
            jListeRecette.removeLastPanel();
            prixTmp -= lastComp.getPrix();
            lstComp.remove(lastComp);
            jLabelPrix.setText("" + CommonTool.round(prixTmp, 4));
            if (lstComp.isEmpty()) {
                jButtonSupI.setEnabled(false);
            }
        }
    }//GEN-LAST:event_jButtonSupIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjoutCommande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjoutCommande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjoutCommande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjoutCommande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AjoutCommande dialog = new AjoutCommande(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAI;
    private javax.swing.JButton jButtonSupI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelPrix;
    private javax.swing.JLabel jLabelPrix2;
    private client.gui.objets.element.JListeRecette jListeRecette;
    private javax.swing.JTextField jTextNom;
    // End of variables declaration//GEN-END:variables
}
