/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package client.gui.objets.element;

import resto.persistance.dto.IngredientDto;

/**
 *
 * @author Gilles
 */
public class JPanelIngre extends javax.swing.JPanel {

    /**
     * Creates new form JPanelIngre
     */
    public JPanelIngre(IngredientDto ing) {
        initComponents();
        jLabelNom.setText(ing.getId().getLibelle());
        jLabelQuantité.setText("" + ing.getQte());
        jLabelPrix.setText("" + ing.getPrix() + " €");
        jLabelUnite.setText(ing.getUnit().toString());
        jLabelFou.setText(ing.getId().getFournisseur());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNom = new javax.swing.JLabel();
        jLabelQuantité = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelPrix = new javax.swing.JLabel();
        jLabelUnite = new javax.swing.JLabel();
        jLabelFou = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(32767, 50));

        jLabelNom.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jLabelNom.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelNom.setText("[Nom]");

        jLabelQuantité.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jLabelQuantité.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelQuantité.setText("[Quantité]");

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("-");

        jLabel2.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText(":");

        jLabelPrix.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jLabelPrix.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPrix.setText("[Prix]");

        jLabelUnite.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jLabelUnite.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelUnite.setText("[Unite]");

        jLabelFou.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jLabelFou.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelFou.setText("[Fournisseur]");

        jLabel3.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelFou)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelQuantité)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelUnite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelPrix)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNom)
                    .addComponent(jLabelQuantité)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabelPrix)
                    .addComponent(jLabelUnite)
                    .addComponent(jLabelFou)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelFou;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelPrix;
    private javax.swing.JLabel jLabelQuantité;
    private javax.swing.JLabel jLabelUnite;
    // End of variables declaration//GEN-END:variables
}
