/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package client.gui.recherche;

import be.esi.alg2.gui.outils.JDRechGenerique;
import be.esi.alg2.gui.outils.MaJTableInitialisationException;
import java.util.Collection;
import javax.swing.ImageIcon;
import resto.business.AdminFacade;
import resto.exception.RestoBusinessException;
import client.gui.criteres.JPCritSelAliment;
import client.gui.table.MaJTableAliment;
import resto.persistance.dto.AlimentDto;
import resto.seldto.AlimentSel;

/**
 *
 * @author g38302
 */
public class JDRechercheAliment extends JDRechGenerique<AlimentSel, AlimentDto> {

    public JDRechercheAliment(java.awt.Frame parent, boolean modal, String title, JPCritSelAliment crit, MaJTableAliment jT) {
        super(parent, modal, title, crit, jT);
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(this.getClass().getResource("/img/Logo.jpg")).getImage());
    }

    @Override
    protected Collection<AlimentDto> recherche(AlimentSel crit) throws RestoBusinessException {
        return AdminFacade.getAliment(crit);
    }

    public static void main(String[] args) throws MaJTableInitialisationException {
        new JDRechercheAliment(null, true, "Sélection d'un Aliment", new JPCritSelAliment(),
                new MaJTableAliment()).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
