/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package client.gui.recherche;

import be.esi.alg2.gui.outils.JDRechGenerique;
import be.esi.alg2.gui.outils.MaJTableInitialisationException;
import java.util.Collection;
import javax.swing.ImageIcon;
import resto.business.AdminFacade;
import client.gui.criteres.JPCritSelCommande;
import client.gui.table.MaJTableCommande;
import common.dto.CommandeDto;
import common.exception.RestoBusinessException;
import common.seldto.CommandeSel;

/**
 *
 * @author g38302
 */
public class JDRechercheCommande extends JDRechGenerique<CommandeSel, CommandeDto> {

    public JDRechercheCommande(java.awt.Frame parent, boolean modal, String title, JPCritSelCommande crit, MaJTableCommande jT) {
        super(parent, modal, title, crit, jT);
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(this.getClass().getResource("/img/Logo.jpg")).getImage());
    }

    @Override
    protected Collection<CommandeDto> recherche(CommandeSel crit) throws RestoBusinessException {
        return AdminFacade.getCommande(crit);
    }

    public static void main(String[] args) throws MaJTableInitialisationException {
        new JDRechercheCommande(null, true, "Sélection d'une recette", new JPCritSelCommande(),
                new MaJTableCommande()).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
