/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package client.gui.recherche;

import java.util.Collection;
import client.gui.criteres.JPCritSelRecette;
import client.gui.table.MaJTableRecette;
import client.implementation.FoodClientImpl;
import client.tools.GenericRecherche;
import common.dto.RecetteDto;
import common.seldto.RecetteSel;
import common.tools.CaseEnum;
import java.rmi.RemoteException;

/**
 *
 * @author g38302
 */
public class JDRechercheRecette extends GenericRecherche<RecetteSel, RecetteDto> {

    public JDRechercheRecette(java.awt.Frame parent, boolean modal,FoodClientImpl modele, String title, JPCritSelRecette crit, MaJTableRecette jT) {
        super(parent, modal,modele, title, crit, jT);
    }

    @Override
    protected Collection<RecetteDto> recherche(RecetteSel crit) throws RemoteException {
        return modele.getBySel(CaseEnum.RECETTE, crit);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
